# coding: utf-8
# Generated by Django 2.1.4 on 2018-12-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depos_app', '0002_album_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='upload',
            field=models.FileField(blank=True, default='', upload_to='depos_app', verbose_name='Файл'),
        ),
    ]
